// packages/wtool-vdiff/src/DiffViewer.vue
<template>
  <div class="diff-viewer-wrap">
    <MonacoDiffViewer 
      :originalCode="originalCode"
      :modifiedCode="modifiedCode"
      :language="language" 
      :options="options" 
      :modelOptions="modelOptions" 
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount, computed } from 'vue'
import MonacoDiffViewer from './MonacoDiffViewer.vue';

import type{ DiffEditorOptions, ModelOptions } from './props'

const props = withDefaults(
  defineProps<{
    diffPair?: { filename: string; content: string }[]
    diffPatch?: string
    language?: string
    options?: DiffEditorOptions
    modelOptions?: ModelOptions
    width?: string
    height?: string
  }>(),
  {
    diffPair: () => [],
    diffPatch: '',
    language: 'plaintext',
    options: () => ({}),
    modelOptions: () => ({}),
    width: '100%',
    height: '400px',
  },
)

const originalCode = computed(() => props.diffPair[0].content)
const modifiedCode = computed(() => props.diffPair[1].content)


</script>

<style scoped>
.diff-viewer-wrap {
  min-height: 200px;
}
</style>

// packages/wtool-diff/src/DiffViewer.svelte
<script lang="ts">
  import type * as Monaco from 'monaco-editor'
  import MonacoEditor from './MonacoEditor.svelte'

  type DiffEditorOptions = Monaco.editor.IStandaloneDiffEditorConstructionOptions
  type ModelOptions = Monaco.editor.ITextModelUpdateOptions

  let {
    originalCode = '',
    modifiedCode = '',
    language = 'plaintext',
    options = {},
    modelOptions = {},
    width = '100%',
    height = '400px',
  }: {
    originalCode?: string
    modifiedCode?: string
    language?: string
    options?: DiffEditorOptions
    modelOptions?: ModelOptions
    width?: string
    height?: string
  } = $props()
</script>

<div class="diff-view-wrap">
  <MonacoEditor
    {originalCode}
    {modifiedCode}
    {language}
    {options}
    {modelOptions}
    {width}
    {height}
  />
</div>

<style>
  .diff-view-wrap {
    min-height: 200px;
  }
</style>
